name: Generate App Name
description: Generates application name based on build type and commit hash.

inputs:
  build-type:
    required: true
    type: string
outputs:
  app-name:
    description: "Application name"
    value: ${{ steps.generate.outputs.app-name }}

runs:
  using: "composite"
  steps:
    - name: Generate
      id: generate
      shell: bash
      run: |
        SHORT_SHA=$(git rev-parse --short HEAD)
        APP_NAME="com.joganera.workouttimer-${{ inputs.build-type }}-${SHORT_SHA}"
        echo "app-name=$APP_NAME" >> $GITHUB_OUTPUT
