name: Build Android

on:
  workflow_call:
    inputs:
      build-type:
        required: true
        type: string
      os:
        required: true
        type: string

jobs:
  build-android:
    runs-on: ${{ inputs.os }}

    steps:
    - name: Generate codegen
      working-directory: android
      run: ./gradlew generateCodegenArtifactsFromSchema

    - name: Build APK
      working-directory: android
      run: ./gradlew assemble${{ inputs.build-type == 'release' && 'Release' || 'Debug' }}
