name: Setup Keystore

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
    secrets:
      MYAPP_UPLOAD_STORE_BASE64:
        required: true
      MYAPP_UPLOAD_STORE_FILE:
        required: true
      MYAPP_UPLOAD_STORE_PASSWORD:
        required: true
      MYAPP_UPLOAD_KEY_ALIAS:
        required: true
      MYAPP_UPLOAD_KEY_PASSWORD:
        required: true

jobs:
  setup-keystore:
    runs-on: ${{ inputs.os }}

    steps:
    - name: Decode keystore
      run: echo "${{ secrets.MYAPP_UPLOAD_STORE_BASE64 }}" | base64 --decode > "android/app/${{ secrets.MYAPP_UPLOAD_STORE_FILE }}"

    - name: Create gradle.properties
      run: |
        mkdir -p "$HOME/.gradle"
        echo "MYAPP_UPLOAD_STORE_FILE=${{ secrets.MYAPP_UPLOAD_STORE_FILE }}" >> "$HOME/.gradle/gradle.properties"
        echo "MYAPP_UPLOAD_KEY_ALIAS=${{ secrets.MYAPP_UPLOAD_KEY_ALIAS }}" >> "$HOME/.gradle/gradle.properties"
        echo "MYAPP_UPLOAD_STORE_PASSWORD=${{ secrets.MYAPP_UPLOAD_STORE_PASSWORD }}" >> "$HOME/.gradle/gradle.properties"
        echo "MYAPP_UPLOAD_KEY_PASSWORD=${{ secrets.MYAPP_UPLOAD_KEY_PASSWORD }}" >> "$HOME/.gradle/gradle.properties"
