name: Android

on:
  push:
    branches:
      - 'main'
      - 'develop'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
        - 'main'
        - 'develop'
    paths-ignore:
        - '**.md'

jobs:
  build-debug:
    uses: ./.github/workflows/android-build-debug.yml
  build-release:
    uses: ./.github/workflows/android-build-release.yml
    secrets:
        MYAPP_UPLOAD_STORE_BASE64: ${{ secrets.MYAPP_UPLOAD_STORE_BASE64 }}
        MYAPP_UPLOAD_STORE_FILE: ${{ secrets.MYAPP_UPLOAD_STORE_FILE }}
        MYAPP_UPLOAD_STORE_PASSWORD: ${{ secrets.MYAPP_UPLOAD_STORE_PASSWORD }}
        MYAPP_UPLOAD_KEY_ALIAS: ${{ secrets.MYAPP_UPLOAD_KEY_ALIAS }}
        MYAPP_UPLOAD_KEY_PASSWORD: ${{ secrets.MYAPP_UPLOAD_KEY_PASSWORD }}
