name: Android Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build-release:
    uses: ./.github/workflows/android-build-release.yml
    secrets:
      MYAPP_UPLOAD_STORE_BASE64: ${{ secrets.MYAPP_UPLOAD_STORE_BASE64 }}
      MYAPP_UPLOAD_STORE_FILE: ${{ secrets.MYAPP_UPLOAD_STORE_FILE }}
      MYAPP_UPLOAD_STORE_PASSWORD: ${{ secrets.MYAPP_UPLOAD_STORE_PASSWORD }}
      MYAPP_UPLOAD_KEY_ALIAS: ${{ secrets.MYAPP_UPLOAD_KEY_ALIAS }}
      MYAPP_UPLOAD_KEY_PASSWORD: ${{ secrets.MYAPP_UPLOAD_KEY_PASSWORD }}

  setup-version:
    needs: build-release
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.setup-version.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup version
        id: setup-version
        uses: ./.github/actions/setup-version

  release:
    needs: [build-release, setup-version]
    runs-on: ubuntu-24.04

    steps:
      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build-release.outputs.apk-name }}

      - name: Rename APK
        run: |
          APK_OLD_NAME="${{ needs.build-release.outputs.apk-name }}"
          APK_NEW_NAME="com.joganera.workouttimer-${{ needs.setup-version.outputs.version }}"
          mv "$APK_OLD_NAME.apk" "$APK_NEW_NAME.apk"
          echo "APK_NAME=$APK_NEW_NAME" >> $GITHUB_ENV

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.APK_NAME }}.apk
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
