name: Android Build [Release]

on:
  workflow_call:
    outputs:
      apk-name:
        value: ${{ jobs.build-release.outputs.apk-name }}
    secrets:
      MYAPP_UPLOAD_STORE_BASE64:
        required: true
      MYAPP_UPLOAD_STORE_FILE:
        required: true
      MYAPP_UPLOAD_STORE_PASSWORD:
        required: true
      MYAPP_UPLOAD_KEY_ALIAS:
        required: true
      MYAPP_UPLOAD_KEY_PASSWORD:
        required: true
  workflow_dispatch:

jobs:
  build-release:
    uses: ./.github/workflows/android-build.yml
    with:
      build-type: release
    secrets:
      MYAPP_UPLOAD_STORE_BASE64: ${{ secrets.MYAPP_UPLOAD_STORE_BASE64 }}
      MYAPP_UPLOAD_STORE_FILE: ${{ secrets.MYAPP_UPLOAD_STORE_FILE }}
      MYAPP_UPLOAD_STORE_PASSWORD: ${{ secrets.MYAPP_UPLOAD_STORE_PASSWORD }}
      MYAPP_UPLOAD_KEY_ALIAS: ${{ secrets.MYAPP_UPLOAD_KEY_ALIAS }}
      MYAPP_UPLOAD_KEY_PASSWORD: ${{ secrets.MYAPP_UPLOAD_KEY_PASSWORD }}
