name: Android Build [Debug]

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-debug:
    strategy:
      matrix:
        node-version: [ '18.x', '23.x' ]
      fail-fast: false

    uses: ./.github/workflows/android-build.yml
    with:
      build-type: debug
      node-version: ${{ matrix.node-version }}
