name: Android Build

on:
  workflow_call:
    inputs:
      build-type:
        required: true
        type: string
    outputs:
      apk_name:
        description: "Name of the generated APK"
        value: ${{ jobs.build.outputs.apk_name }}
    secrets:
      MYAPP_UPLOAD_STORE_BASE64:
        required: false
      MYAPP_UPLOAD_STORE_FILE:
        required: false
      MYAPP_UPLOAD_STORE_PASSWORD:
        required: false
      MYAPP_UPLOAD_KEY_ALIAS:
        required: false
      MYAPP_UPLOAD_KEY_PASSWORD:
        required: false

jobs:
  setup-environment:
    uses: ./.github/workflows/reusable/setup-environment.yml
    with:
      node-version: '23'
      os: 'ubuntu-24.04'
  
  setup-keystore:
    if: ${{ inputs.build-type == 'release' }}
    needs: setup-environment
    uses: ./.github/workflows/reusable/setup-keystore.yml
    with:
      build-type: ${{ inputs.build-type }}
      os: 'ubuntu-24.04'
    secrets:
      MYAPP_UPLOAD_STORE_BASE64: ${{ secrets.MYAPP_UPLOAD_STORE_BASE64 }}
      MYAPP_UPLOAD_STORE_FILE: ${{ secrets.MYAPP_UPLOAD_STORE_FILE }}
      MYAPP_UPLOAD_STORE_PASSWORD: ${{ secrets.MYAPP_UPLOAD_STORE_PASSWORD }}
      MYAPP_UPLOAD_KEY_ALIAS: ${{ secrets.MYAPP_UPLOAD_KEY_ALIAS }}
      MYAPP_UPLOAD_KEY_PASSWORD: ${{ secrets.MYAPP_UPLOAD_KEY_PASSWORD }}

  extract-version:
    needs: setup-keystore
    uses: ./.github/workflows/reusable/extract-version.yml
    with:
      os: 'ubuntu-24.04'

  build-android:
    needs: extract-version
    uses: ./.github/workflows/reusable/build-android.yml
    with:
      build-type: ${{ inputs.build-type }}
      os: 'ubuntu-24.04'

  apk-management:
    needs: build-android
    uses: ./.github/workflows/apk-management.yml
    with:
      build-type: ${{ inputs.build-type }}
      os: 'ubuntu-24.04'
      version: ${{ needs.extract-version.outputs.version }}
