name: android

on:
    push:
        branches:
            - 'master'
            - 'develop'
        paths-ignore:
            - '**.md'
    pull_request:
        branches:
            - 'master'
            - 'develop'
        paths-ignore:
            - '**.md'

jobs:
    build:
        name: Build Android
        runs-on: ${{matrix.os}}
        strategy:
            matrix:
                os: [ ubuntu-24.04 ]
                build_type: [ assembleDebug, assembleRelease ]
                node-version: [ '18.x' ]
            fail-fast: false

        steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up Java
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: '17'

        - name: Set up Node
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}

        - name: Install dependencies
          run: npm install

        - name: Run Lint
          run: npm run lint

        - name: Cache Gradle
          uses: actions/cache@v4
          with:
            path: |
                ~/.gradle/caches
                ~/.gradle/wrapper
            key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
            restore-keys: |
                ${{ runner.os }}-gradle-

        - name: Build
          working-directory: android
          run: ./gradlew ${{matrix.build_type}}

        # - name: Upload
        #   uses: actions/upload-artifact@v4
        #   with:
        #     name: WorkoutTimer
        #     path: android/app/build/outputs/apk/debug/WorkoutTimer.apk
