name: Android Build [Debug]

on:
  workflow_call:
    outputs:
      apk-name:
        value: ${{ jobs.build-debug.outputs.apk-name }}
  workflow_dispatch:

jobs:
  build-debug:
    uses: ./.github/workflows/android-build.yml
    with:
      build-type: debug
