name: Android Build

on:
  workflow_call:
    inputs:
      build-type:
        required: true
        type: string
    outputs:
      apk-name:
        value: ${{ jobs.build.outputs.apk-name }}
    secrets:
      MYAPP_UPLOAD_STORE_BASE64:
        required: false
      MYAPP_UPLOAD_STORE_FILE:
        required: false
      MYAPP_UPLOAD_STORE_PASSWORD:
        required: false
      MYAPP_UPLOAD_KEY_ALIAS:
        required: false
      MYAPP_UPLOAD_KEY_PASSWORD:
        required: false

jobs:
  build:
    runs-on: ${{matrix.os}}
    outputs:
      apk-name: ${{ steps.generate-apk-name.outputs.app-name }}
    strategy:
      matrix:
        os: [ ubuntu-24.04 ]
        node-version: [ '23' ]
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run Lint
      run: npm run lint

    - name: Cache Gradle
      uses: actions/cache@v4
      with:
        path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
            ${{ runner.os }}-gradle-

    - name: Setup keystore
      if: ${{ inputs.build-type == 'release' }}
      uses: ./.github/actions/setup-keystore
      with:
        upload-store-base64: ${{ secrets.MYAPP_UPLOAD_STORE_BASE64 }}
        upload-store-file: ${{ secrets.MYAPP_UPLOAD_STORE_FILE }}
        upload-store-password: ${{ secrets.MYAPP_UPLOAD_STORE_PASSWORD }}
        upload-key-alias: ${{ secrets.MYAPP_UPLOAD_KEY_ALIAS }}
        upload-key-password: ${{ secrets.MYAPP_UPLOAD_KEY_PASSWORD }}

    - name: Generate codegen
      working-directory: android
      run: ./gradlew generateCodegenArtifactsFromSchema

    - name: Build APK
      working-directory: android
      run: ./gradlew assemble${{ inputs.build-type == 'release' && 'Release' || 'Debug' }} -PreactNativeArchitectures=armeabi-v7a,arm64-v8a

    - name: Generate APK name
      id: generate-apk-name
      uses: ./.github/actions/generate-app-name
      with:
        build-type: ${{ inputs.build-type }}

    - name: Rename APK
      run: |
        mv android/app/build/outputs/apk/${{ inputs.build-type }}/app-${{ inputs.build-type }}.apk android/app/build/outputs/apk/${{ inputs.build-type }}/${{ steps.generate-apk-name.outputs.app-name }}.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.generate-apk-name.outputs.app-name }}
        path: android/app/build/outputs/apk/${{ inputs.build-type }}/${{ steps.generate-apk-name.outputs.app-name }}.apk
